### ISSUE TITLE
No light in pt: proper error message

### ISSUE THREAD

**Issue by Luvideria** [lightmetrica/lightmetrica-v3#12]
When using a scene without emissive materials and no envmap, the resulting frame should either be fully black or an error message displayed.
Currently, the error is:

`IndexError: vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 0)`

A test could be placed with the subsequent warning message:
"Warning: there is no light in the scene, returning black frame"

**Comment by hi2p-perim** [comment]
fixed by #13
